vae:
  io:
    data_folder: 'd:/tmp/celeb'
    zip_file: 'd:/Python_datasets/celeba_10000.zip'
    image_size: 128
    section: vae
    run_id: '0032'
    data_name: celeb
  exec:
    mode: build
    batch_size: 10
    epochs: 25
    print_batches: 100

  logger:
    file_name: vae.log
    log_level: 10
    console_level: 10

wgangp:
  io:
    data_folder: 'd:/tmp/celeb'
    zip_file: 'd:/Python_datasets/celeba_10000.zip'
    image_size: 64
    section: wgangp
    run_id: '001'
    data_name: celeb

  exec:
    mode: build
    batch_size: 10
    epochs: 1000
    print_batches: 50

  logger:
    file_name: wgangp.log
    log_level: 10
    console_level: 10

camel:
  io:
    data_folder: 'd:/Python_datasets/camel'
    data_file: full_numpy_bitmap_camel.npy
    section: gan
    run_id: '001'
    data_name: camel
    image_quantity: 80000

  exec:
    mode: build
    batch_size: 10
    epochs: 100
    print_batches: 20

  logger:
    file_name: camel.log
    log_level: 10
    console_level: 10










